// =============================================================================
// LogManagerBPFunctionLibrary.h
// LogManager Plugin for Unreal Engine 5
//
// Copyright (c) 2025 AIPIC Team, Research Center of Saint-Cyr Coetquidan
// All rights reserved.
//
// This file is part of the LogManager Plugin, licensed under the
// Creative Commons Attribution-NonCommercial 4.0 International License
// (CC BY-NC 4.0) with additional terms for software usage.
//
// You are free to:
//   - Share: copy and redistribute the material in any medium or format
//   - Adapt: remix, transform, and build upon the material
//
// Under the following terms:
//   - Attribution: You must give appropriate credit to the AIPIC Team,
//     Research Center of Saint-Cyr Coetquidan, provide a link to the license,
//     and indicate if changes were made.
//   - NonCommercial: You may not use the material for commercial purposes.
//
// Additional Terms for Software Usage:
//   - This plugin may be integrated into Unreal Engine projects for research,
//     educational, and non-commercial purposes only.
//   - Any derivative work or project using this plugin must retain this header
//     and provide attribution in accompanying documentation.
//   - Redistribution of this plugin, modified or unmodified, must preserve
//     this license header and must not be sold or sublicensed.
//
// Full license text: https://creativecommons.org/licenses/by-nc/4.0/legalcode
//
// For commercial licensing inquiries, contact:
//   AIPIC Team - Research Center of Saint-Cyr Coetquidan
// =============================================================================

/**
 * @file LogManagerBPFunctionLibrary.h
 * @brief Blueprint Function Library exposing all LogManager logging operations to Blueprints.
 *
 * ULogManagerBPFunctionLibrary is the Blueprint-facing API of the LogManager plugin.
 * It provides a set of static functions callable from both C++ and Unreal Engine Blueprints,
 * grouped under the "LOGLibrary" category in the Blueprint editor.
 *
 * Each function delegates its work to FLogManagerModule, which manages the underlying
 * third-party shared library responsible for writing JSON log files.
 *
 * Typical usage flow in a Blueprint session:
 *   1. GetConfigFileInfos()      — read the current participant ID and XP setting
 *   2. WriteLog_StartSurvey()    — record the pre-XP survey in a separate file 
 *                                  (only once per participant)
 *   3. WriteLog_XPStart()        — open a new log file and record the XP start event
 *   4. WriteLog_CubeInteraction() / WriteLog_BoxEvent() — record in-session events
 *   5. WriteLog_XPStop()         — record the XP end event and close the log file
 *   6. WriteLog_FinalSurvey()    — append the final survey answers to the current file
 *   7. Loop step 3 to 6 with the same participant or
 *      CreateNewConfigFile()     — increment the participant ID and cycle the setting
 */

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "LogManagerBPFunctionLibrary.generated.h"

UCLASS()
class LOGMANAGER_API ULogManagerBPFunctionLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	/**
	 * Records the start of an XP (experiment) run.
	 * Creates and opens a new timestamped JSON log file, then writes an XP_START event
	 * containing the participant ID, current experiment setting, and initial head/player location.
	 *
	 * File naming convention: YYYY-MM-DD_HHhMMmSSs_id<userId>_<setting>.json
	 *
	 * @param gameTime         In-game time (seconds) at the moment of the XP start.
	 * @param userId           Unique identifier of the current participant.
	 * @param currentSetting   Current experiment condition (table position).
	 * @param startLocation    World-space position of the player at XP start.
	 */
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "XP Start"), Category = "LOGLibrary")
	static void WriteLog_XPStart(float gameTime, int64 userId, ESetting currentSetting, FVector startLocation);

	/**
	 * Records the end of an XP (experiment) run.
	 * Writes an XP_STOP event to the currently open log file, then closes it.
	 * The presence of this event in the file confirms that the XP session completed normally.
	 *
	 * @param gameTime  In-game time (seconds) at the moment of the XP stop.
	 */
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "XP Stop"), Category = "LOGLibrary")
	static void WriteLog_XPStop(float gameTime);

	/**
	 * Creates a new config.json file with the next participant ID and the next experiment setting.
	 * The participant ID is generated by incrementing the previous one via GetNextID().
	 * The setting cycles through all ESetting values in order (wraps around using ESetting::Count).
	 *
	 * This function should be called between each XP session to prepare for the next participant.
	 *
	 * @param previousUserId    ID of the participant who just completed the XP.
	 * @param previousSetting   Setting used during the just-completed XP.
	 * @param nextId            [out] Generated ID for the next participant.
	 * @param nextSetting       [out] Setting to be used for the next participant.
	 */
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Create Config File"), Category = "LOGLibrary")
	static void CreateNewConfigFile(int64 previousUserId, ESetting previousSetting, int64& nextId, ESetting& nextSetting);

	/**
	 * Reads the current participant ID and experiment setting from the config.json file.
	 * Should be called at the beginning of a session to initialize the XP parameters.
	 *
	 * @param userId           [out] Participant ID read from the config file.
	 * @param currentSetting   [out] Experiment setting read from the config file.
	 * @return                 True if the config file was successfully read and parsed, false otherwise.
	 */
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Get Config File Infos"), Category = "LOGLibrary")
	static bool GetConfigFileInfos(int64& userId, ESetting& currentSetting);

	/**
	 * Records the start-of-XP survey results in a dedicated log file.
	 * Creates and opens a new timestamped JSON file named with the participant ID and "_startSurvey",
	 * writes a START_SURVEY event, then closes the file.
	 *
	 * @param gameTime     In-game time (seconds) at the moment the survey was submitted.
	 * @param userId       Unique identifier of the current participant.
	 * @param evaluation   Participant's self-evaluation score (numeric rating).
	 * @param usefullness  Whether the participant found the XP setup useful (true/false).
	 * @param comment      Free-text comment provided by the participant.
	 */
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Start Survey"), Category = "LOGLibrary")
	static void WriteLog_StartSurvey(float gameTime, int64 userId, int evaluation, bool usefullness, FString comment);

	/**
	 * Records the final survey answers in the currently open log file.
	 * Writes a FINAL_SURVEY event containing all question-answer pairs as a nested JSON object.
	 * The log file must already be open (e.g., from a prior WriteLog_XPStart() call).
	 *
	 * @param gameTime             In-game time (seconds) at the moment the survey was submitted.
	 * @param questionsAndAnswers  Map of question strings to their corresponding answer strings.
	 */
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Final Survey"), Category = "LOGLibrary")
	static void WriteLog_FinalSurvey(float gameTime, TMap<FString, FString> questionsAndAnswers);

	/**
	 * Records a participant interaction with a grabbable cube object.
	 * Writes a CUBE_INTERACTION event to the currently open log file.
	 *
	 * @param gameTime   In-game time (seconds) at the moment of the interaction.
	 * @param isGrabbed  True if the cube was grabbed, false if it was released.
	 * @param timer      Duration (in seconds) since the last interaction with this cube.
	 * @param distance   Distance (in Unreal units) between the participant and the cube.
	 * @param name       Identifier name of the cube object involved in the interaction.
	 */
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Cube Interaction"), Category = "LOGLibrary")
	static void WriteLog_CubeInteraction(float gameTime, bool isGrabbed, float timer, int64 distance, FName name);

	/**
	 * Records a participant entering or exiting a defined spatial zone (box trigger).
	 * Writes a BOX_EVENT event to the currently open log file.
	 *
	 * @param gameTime  In-game time (seconds) at the moment of the box event.
	 * @param number    Index or identifier of the box/zone that triggered the event.
	 * @param location  World-space position of the box trigger at the time of the event.
	 * @param inside    True if the participant entered the zone, false if they exited it.
	 */
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Box Event"), Category = "LOGLibrary")
	static void WriteLog_BoxEvent(float gameTime, int32 number, FVector location, bool inside);
};
